---
# Simple PlayBook to create the initial stacks for CICD

- name: Initialize CICD resources
  hosts:
    - localhost
  vars:
    debug: false
    use_stricly_roles_access: true
  tasks:
    - name: Get CICD AWS Account details
      amazon.aws.aws_caller_info:
        profile: "{{ cicd_account_profile }}"
      register: cicd_account_info

    - name: Get NonProd AWS Account details
      amazon.aws.aws_caller_info:
        profile: "{{ nonprod_account_profile }}"
      register: nonprod_account_info

    - name: Get Prod AWS Account details
      amazon.aws.aws_caller_info:
        profile: "{{ prod_account_profile }}"
      register: prod_account_info

    - name: Create KMS Key Stack
      amazon.aws.cloudformation:
        profile: "{{ cicd_account_profile }}"
        stack_name: "cicd--kms-key"
        state: "present"
        disable_rollback: true
        termination_protection: true
        template: "templates/cicd_kms_key.template"
        template_parameters:
          ProdAccountId: "{{ prod_account_info.account }}"
          NonProdAccountId: "{{ nonprod_account_info.account }}"
        tags:
          Usage: CICD-KMS
      register: kms_key_stack

    - name: Create S3 Bucket
      amazon.aws.cloudformation:
        profile: "{{ cicd_account_profile }}"
        stack_name: "cicd--buckets"
        state: "present"
        disable_rollback: true
        termination_protection: false
        template: "templates/cicd_s3_buckets.template"
        template_parameters:
          ProdAccountId: "{{ prod_account_info.account }}"
          NonProdAccountId: "{{ nonprod_account_info.account }}"
          ArtifactsBucketPrefix: shared-codepipeline
          TemplatesBucketPrefix: shared-cfn-templates
        tags:
          Usage: CICD-KMS
      register: cicd_buckets_stack

    - name: Create NonProd IAM Roles
      amazon.aws.cloudformation:
        profile: "{{ nonprod_account_profile }}"
        stack_name: "cicd--iam-roles"
        state: "present"
        disable_rollback: false
        termination_protection: false
        capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
        template: "templates/cicd_iam_roles.template"
        template_parameters:
          CICDAccountId: "{{ cicd_account_info.account }}"
          KmsKeyArn: "{{ kms_key_stack.stack_outputs.KmsKeyArnMgmt }}"
          ArtifactsBucketArn: "{{ cicd_buckets_stack.stack_outputs.ArtifactsBucketArn }}"
          CloudformationTemplatesBucketArn: "{{ cicd_buckets_stack.stack_outputs.CloudformationTemplatesBucketArn }}"
          PermissionsBoundary: "{%if nonprod_boundary_policy%}{{nonprod_boundary_policy}}{%else%}none{%endif%}"
        tags:
          Usage: CICD-IAM-Roles
      register: nonprod_iam_roles_stack

    - name: Create Prod IAM Roles
      amazon.aws.cloudformation:
        profile: "{{ prod_account_profile }}"
        stack_name: "cicd--iam-roles"
        state: "present"
        disable_rollback: false
        termination_protection: false
        capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
        template: "templates/cicd_iam_roles.template"
        template_parameters:
          CICDAccountId: "{{ cicd_account_info.account }}"
          KmsKeyArn: "{{ kms_key_stack.stack_outputs.KmsKeyArnMgmt }}"
          ArtifactsBucketArn: "{{ cicd_buckets_stack.stack_outputs.ArtifactsBucketArn }}"
          CloudformationTemplatesBucketArn: "{{ cicd_buckets_stack.stack_outputs.CloudformationTemplatesBucketArn }}"
          PermissionsBoundary: "{%if prod_boundary_policy%}{{prod_boundary_policy}}{%else%}none{%endif%}"
        tags:
          Usage: CICD-IAM-Roles
      register: prod_iam_roles_stack

    - name: Create cross-accounts Settings IAM Roles for re-use in CICD Account
      amazon.aws.cloudformation:
        profile: "{{ cicd_account_profile }}"
        stack_name: "cicd--crossaccounts-iam-roles"
        state: "present"
        disable_rollback: false
        termination_protection: false
        template: "templates/cicd_mgmt_settings.template"
        template_parameters:
          NonProdAccountId: "{{ nonprod_account_info.account }}"
          NonProdAccountCfnRoleId: "{{ nonprod_iam_roles_stack.stack_outputs.CfnRoleId }}"
          NonProdAccountCfnRoleArn: "{{ nonprod_iam_roles_stack.stack_outputs.CfnRoleArn }}"
          NonProdAccountPipelineRoleArn: "{{ nonprod_iam_roles_stack.stack_outputs.CrossRoleArn }}"
          NonProdAccountPipelineRoleId: "{{ nonprod_iam_roles_stack.stack_outputs.CrossRoleId }}"
          NonProdAccountReadOnlyRoleArn: "{{ nonprod_iam_roles_stack.stack_outputs.CrossReadOnlyRoleArn }}"

          ProdAccountId: "{{ prod_account_info.account }}"
          ProdAccountCfnRoleId: "{{ prod_iam_roles_stack.stack_outputs.CfnRoleId }}"
          ProdAccountCfnRoleArn: "{{ prod_iam_roles_stack.stack_outputs.CfnRoleArn }}"
          ProdAccountPipelineRoleArn: "{{ prod_iam_roles_stack.stack_outputs.CrossRoleArn }}"
          ProdAccountPipelineRoleId: "{{ prod_iam_roles_stack.stack_outputs.CrossRoleId }}"
          ProdAccountReadOnlyRoleArn: "{{ prod_iam_roles_stack.stack_outputs.CrossReadOnlyRoleArn }}"

        tags:
          Usage: CICD-CrossAccount-Settings
      register: cicd_mgmt_settings
