{% if cookiecutter.runtime == "java" %}
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: mvn
{% elif cookiecutter.runtime == "python" %}
version: 2
updates:
  - package-ecosystem: "pip" # If you use poetry, change to `poetry`
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: pip
{% else %}
# Example. Update accordingly. See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
# version: 2
# updates:
#   - package-ecosystem: "maven"
#     directory: "/"
#     schedule:
#       interval: "daily"
#     commit-message:
#       prefix: mvn
{% endif %}
