---
# nominal docker compose file

version: "3.8"
services:
  {{ cookiecutter.app_name }}:
    build:
      context: .
      dockerfile: Dockerfile
{% if cookiecutter.runtime == "java" %}
      args:
        JAR_FILE: ${JAR_FILE}
{% endif %}
    image: ${REGISTRY_URI}{{ cookiecutter.repository_name }}:${IMAGE_TAG:-latest}
    deploy:
      replicas: 2
      resources:
        reservations:
          cpus: 0.5
          memory: 1GB
    logging:
      driver: awsfirelens
      options:
        Name: cloudwatch
    x-logging:
      FireLens:
        Advanced:
          SourceFile: logging/filters.conf
          EnableApiHeathCheck: true
          GracePeriod: 60
{% if cookiecutter.runtime == "java" %}
          ParserFiles:
            - logging/spring_parser.conf
{% endif %}
    x-ecr:
      InterpolateWithDigest: true
